### ISSUE TITLE
babel-interface-dtls-certs

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#20]
The description for the above object says it is a list of references to the babel-dtls entries that apply to this interface. If that is the case, why is the attribute not named babel-interface-dtls-objs or simply babel-dtls-objs?

**Comment by bhstark2** [comment]
Yeah, I was kinda bothered by that too (and interface-hmac-keys). But I'm also bothered by the fact that the  babel-dtls and babel-hmac are just containers for a set of certificates / keys (now that all other parameters have been moved out to the interface), so their names are insufficiently descriptive of what they are. 
What if the objects were renamed babel-dtls-cert-set and babel-hmac-key-set and the interface parameters became interface-dtls-cert-sets and interface-hmac-key-sets?
[I see that in the Section 2 overview I have "interfaces-" instead of "interface-" in the protocol names. That needs fixing, too.]

**Comment by bhstark2** [comment]
Fixed in -09
