### ISSUE TITLE
Why are the following properties ro?

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#21]
These properties are marked ro in the babel-information-obj. Are they really meant to be ro? In that case, how are these set?

babel-supported-link-properties
babel-metric-comp-algorithms
babel-security-supported
babel-hmac-algorithms
babel-dtls-enable
babel-dtls-cert-types
babel-constants
babel-interfaces

**Comment by bhstark2** [comment]
babel-dtls-enable (and babel-hmac-enable) should be rw. That's a mistake. Per recent discussion on the list, those 2 are going to be moved to interface.
babel-constants is a single-instance object that is required to be present in all Babel implementations (that support this info model in some form). The implementation is expected to ensure the single instance is there. If it's already there, it can't be added. And it's not allowed to be deleted (because it has to be there).
babel-interfaces instances are automatically generated by the Babel implementation from the IPv6 interfaces available on the device. The management system can enable or disable Babel on an interface (babel-interface-enable), and it may be able to add and delete IPv6 interfaces on the device. But if an IPv6 interface exists, the implementation is expected to just recognize it and add it. Or if the IPv6 interface goes away, the implementation automatically deletes it from Babel. This is my understanding. It may be useful to confirm with the list, since I'm not always right.
The others you list exist so the implementation can inform the management system about the implementation's capabilities. Implementation capabilities can only be added/deleted/modified by providing a new revision of the implementation (changes to implementation code).

**Comment by mjethanandani** [comment]
On second thoughts, I do agree that babel-interfaces should be ro, as they are system generated.

I take the argument that most of the attributes can/should be changed only with an implementation. Moving to the configuration of some of these attributes under the interface, I notice for an example that babel-interface-metric-algorithm is also ro. Assuming that this is a subset of babel-metric-comp-algorithm, this lists the algorithms that will be supported on a given interface. Could it be that it is a configurable attribute under the interface?

**Comment by bhstark2** [comment]
With the change to having babel-link-properties including in the definition of the property the algorithm used, I don't think we want to allow changing of algorithm used on an interface separate from link-properties assigned to the interface. Link-properties is rw. Technically, the babel-interface-metric-algorithm is unnecessary (redundant) now that link-properties includes it in the definition. But I think it still may be useful to report it separately, from a human usability perspective. Or not?

The definitions that I'll be changing to for the link-properties are the ones Juliusz supplied:
> wired means 2-out-of-3, split-horizon, no RTT.
> wireless means ETX, no split-horizon, no RTT.
> tunnel means 2-out-of-3, split-horizon, RTT.

**Comment by mjethanandani** [comment]
Ok. I do agree that with the new definitions provided by Juliusz for link-properties, reporting the metric-algorithm is redundant AND will be confusing. You can add the above provided definitions to the description of each link-properties. Let us drop metric-algorithm.

**Comment by bhstark2** [comment]
OBE -- no link-properties and extensive discussion on list
For objects, info model and YANG may differ in markings due to what is meant by "rw" in each.
