### ISSUE TITLE
actions

### ISSUE THREAD

**Issue by bhstark2** [bhstark2/babel-information-model#4]
The babel WG wants to be able to add/delete credentials without making them readable. I find "operations" to be good for doing this. Since YANG supports the "action" statement and TR-181 has something similar, I'd like to add a datatype of 
operation: An executable command with input and output parameters.

**Comment by mjethanandani** [comment]
It is true that YANG 'action' command does allow you to setup input and output parameters. And I can see that an action would be needed to delete a key or a certificate. But I am not sure about a add action command. This is supported today by configuring the attribute. To the question of not exposing the key, in YANG, we make note in the model that the read operation should be denied. It would be highly unusual to have an add action command because we wanted to deny a read of the contents. Just my 2 cents.

**Comment by bhstark2** [comment]
I ended up not using actions for add/delete of credentials. But I do still have them for checking the hash created with a private key and for resetting statistics.
