### ISSUE TITLE
babel-dtls-obj list has no key

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#8]
babel-dtls-obj is a list of objects. Looking into the object definition though, there is no key to the list. How does one know which object in the list one is referring to? I think we are missing a name or an id as a member of the list. Compare that to babel-hmac-obj, and there is a name.

**Comment by bhstark2** [comment]
The main reason for the hmac-key-name was because the hmac-key-value wasn't readable. There needed to be some way explicitly identified to know which key this was without knowing what the key value was. With the DTLS certs, the cert-value is unique and readable (it has no private key info) -- so there's not the same need for a name. But cert-value could be quite big, which might make it unsuitable as a table key.
I'm a bit torn about introducing a parameter into the info model just to be a table key. In TR-181, all table instances automatically get both an instance number and "Alias" at instance creation. So I don't need the info model to specify some other key. [For hmac-key-name, I decided the TR-181 Alias parameter served the required purpose and didn't create a separate parameter for it.]
If all certs had been X.509, I would have had the serial number as a parameter. But not all certs will be X.509 or have a serial number. There's nothing I can pull from all of the allowed cert types that makes for a good table key, and I don't want to constrain a data model to use a particular type of table key when different data models do different things for table keying.
Does YANG not have some way to specify a generated-at-entry-creation table key?

**Comment by mjethanandani** [comment]
No. YANG does not have a way to generate a "Alias" on entry. And even if it did, I suspect it would have to write that "Alias" into the same table/list object where it entered the key, i.e. have an id/name mapping for every entry. 

If you feel strongly about it, I will make it particular to the YANG model to have that id/name.

My first reaction was to see if I could somehow use one of the parameters as keys, but could not find one that was unique. That is why you may have noticed in the YANG model, I have a TODO.

I had the same question for list of certs. And I agree that we cannot assume X.509 certs. So if type attribute in certs is not unique, I will need to add an id/name for certs also.

**Comment by bhstark2** [comment]
Per discussion in Prague, I think we agreed not to add a unique parameter to the info model (to serve as a key). YANG will have a unique key added (which I see in the current revision).
