### ISSUE TITLE
Description for babel-implementation-version

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#9]
The description for babel-implementation-version says that it is the "name and version of this implementation". Previously, this said "the version". Why the change, and what is name in this parameter?

**Comment by bhstark2** [comment]
See https://mailarchive.ietf.org/arch/msg/babel/i_NNjLb4whjMMnXCUk4T8bHyo2M
Because there are 6 different implementations of Babel (at this time -- there could be more in the future), people said it was important to know which implementation is being used and what version of that implementation. I don't think it makes sense to try to create an implementation naming or versioning convention -- so the name and version are whatever the implementer says they are. The parameter value is intended for human consumption and interpretation.

**Comment by mjethanandani** [comment]
Ok. I was clearly not paying attention to the discussion back in Oct. 

As Juliusz mentions in the end, I think we should make them two separate fields. One for implementation name and another for implementation version. Anyone trying to figure out which implementation they are dealing with, would have to break up the string into two parts. Why not keep them separate?

**Comment by bhstark2** [comment]
I don't see where Juliusz suggests splitting implementation name and version into 2 fields?
Earlier in that message you'll find Toke says:
> Couldn't this just be a version string that includes both? I.e., the
> 'version' would be 'babeld 1.8.3', or 'bird 2.0' - I think that is what
> e.g. DNS servers do?

And this is consistent with the example Juliusz gives. Which is why I made it a single string that includes both.

What Juliusz discusses at the end of the email message is what we might do in the future if IETF ever created a different version of the Babel protocol, and wanted to represent protocol version in the model. But that was a "not now, maybe later, if that ever happens" statement.

**Comment by mjethanandani** [comment]
Fair enough.
